#!/usr/bin/env python3
"""Pin this worktree's own DATABASE_URL ahead of any ambient env var.

Writes a `sitecustomize.py` into the *active* `.venv`'s site-packages
directory (resolved from the running interpreter via
`sysconfig.get_path("purelib")`, unless overridden). Every Python process
started from that `.venv` auto-imports `sitecustomize` before any user
code - including `src/db.py`'s `load_dotenv()` - so the generated module
can make this worktree's own `.env` win over a `DATABASE_URL` the
launching shell already exports, which `load_dotenv()` alone never does
(see `_docs/decisions.md#26` and `_docs/process.md`'s "Uma pegadinha que
vale saber").

Usage (inside a worktree, once its `.env` exists):

    uv run python scripts/pin_worktree_database.py

`--site-packages-dir` and `--project-root` exist only for the test suite,
to redirect both where the file is written and which `.env` path gets
baked into it, without touching the real interpreter's site-packages or
the real checkout. Real worktree usage never passes either.
"""

import argparse
import sysconfig
from pathlib import Path

SITECUSTOMIZE_TEMPLATE = '''"""Auto-generated by pin_worktree_database.py - do not hand-edit.

Auto-imported by the interpreter before any user code, including
`src/db.py`'s `load_dotenv()`. Re-reads `.env` on every Python startup (it
does not bake a value in once and stop), so it stays correct across `.env`
edits with no need to rerun the generating script - only `.venv` being
recreated (`uv sync`) requires that.
"""

import os
from pathlib import Path

_ENV_PATH = Path({env_path!r})


def _pin_database_url() -> None:
    if not _ENV_PATH.is_file():
        return
    for line in _ENV_PATH.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        key = key.strip()
        if key != "DATABASE_URL":
            continue
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
            value = value[1:-1]
        os.environ["DATABASE_URL"] = value
        return


_pin_database_url()
'''


def _resolve_project_root(project_root: str | None) -> Path:
    if project_root is not None:
        return Path(project_root).resolve()
    return Path(__file__).resolve().parent.parent


def _resolve_site_packages_dir(site_packages_dir: str | None) -> Path:
    if site_packages_dir is not None:
        return Path(site_packages_dir).resolve()
    return Path(sysconfig.get_path("purelib"))


def write_sitecustomize(site_packages_dir: Path, project_root: Path) -> Path:
    """Write (or overwrite) `sitecustomize.py` in `site_packages_dir`.

    Overwriting the whole file on every run - never appending - is what
    keeps this idempotent: running the script twice leaves exactly one
    correct `sitecustomize.py`, not a duplicate.
    """
    site_packages_dir.mkdir(parents=True, exist_ok=True)
    env_path = project_root / ".env"
    content = SITECUSTOMIZE_TEMPLATE.format(env_path=str(env_path))
    target = site_packages_dir / "sitecustomize.py"
    target.write_text(content, encoding="utf-8")
    return target


def main(argv: list[str] | None = None) -> Path:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--site-packages-dir",
        default=None,
        help="Directory to write sitecustomize.py into. Defaults to the "
        "running interpreter's sysconfig.get_path('purelib'). Only the "
        "test suite overrides this.",
    )
    parser.add_argument(
        "--project-root",
        default=None,
        help="Worktree root the generated sitecustomize.py's .env path is "
        "anchored to. Defaults to this script's own worktree root. Only "
        "the test suite overrides this.",
    )
    args = parser.parse_args(argv)
    project_root = _resolve_project_root(args.project_root)
    site_packages_dir = _resolve_site_packages_dir(args.site_packages_dir)
    target = write_sitecustomize(site_packages_dir, project_root)
    print(f"wrote {target}")
    return target


if __name__ == "__main__":
    main()
